/**
 * Client-side export helpers — no server round-trip. Feeds mock data into a
 * downloadable CSV, or opens a print-preview window for PDF export.
 */

export type ExportColumn<T> = { key: keyof T | string; label: string; get?: (row: T) => string | number };

function csvEscape(v: string | number): string {
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCSV<T extends Record<string, unknown>>(rows: T[], columns: ExportColumn<T>[]): string {
  const header = columns.map((c) => csvEscape(c.label)).join(",");
  const body = rows.map((row) =>
    columns
      .map((c) => csvEscape(c.get ? c.get(row) : String(row[c.key as keyof T] ?? "")))
      .join(",")
  );
  return "\uFEFF" + [header, ...body].join("\n"); // BOM for Excel
}

export function downloadCSV<T extends Record<string, unknown>>(filename: string, rows: T[], columns: ExportColumn<T>[]) {
  const blob = new Blob([toCSV(rows, columns)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".csv") ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadPDF<T extends Record<string, unknown>>(
  title: string,
  rows: T[],
  columns: ExportColumn<T>[],
  meta?: { subtitle?: string; footer?: string },
) {
  const w = window.open("", "_blank", "width=900,height=1100");
  if (!w) return;
  const rowHtml = rows
    .map(
      (r) =>
        `<tr>${columns
          .map((c) => `<td>${escapeHtml(String(c.get ? c.get(r) : (r[c.key as keyof T] ?? "")))}</td>`)
          .join("")}</tr>`,
    )
    .join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title>
<style>
  *{box-sizing:border-box}
  body{font-family:-apple-system,BlinkMacSystemFont,'Inter',sans-serif;padding:32px;color:#0f172a}
  h1{font-size:22px;margin:0 0 4px}
  .sub{color:#64748b;font-size:13px;margin-bottom:24px}
  table{width:100%;border-collapse:collapse;font-size:12px}
  th,td{padding:8px 10px;border-bottom:1px solid #e2e8f0;text-align:start}
  th{background:#f1f5f9;text-transform:uppercase;font-size:10px;letter-spacing:.06em;color:#475569}
  tr:nth-child(even) td{background:#f8fafc}
  .foot{margin-top:24px;color:#94a3b8;font-size:11px}
  @media print{@page{margin:12mm}}
</style></head><body>
  <h1>${escapeHtml(title)}</h1>
  <p class="sub">${escapeHtml(meta?.subtitle ?? new Date().toLocaleDateString())}</p>
  <table><thead><tr>${columns.map((c) => `<th>${escapeHtml(c.label)}</th>`).join("")}</tr></thead><tbody>${rowHtml}</tbody></table>
  <p class="foot">${escapeHtml(meta?.footer ?? "Generated by Fiksu")}</p>
  <script>window.onload=()=>{setTimeout(()=>window.print(),200)}</script>
</body></html>`);
  w.document.close();
}

function escapeHtml(s: string) {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
}
